version: "3"

services:

    db:
        image: postgres
        restart: always
        container_name: CHATGPT_DB
        expose:
            - 5432
        ports:
            - "${DB_PORT}:5432"
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
